version: '3.8'

services:
  backend:
    build:
      context: ./backend/coresystem
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: coresystem-backend

  frontend:
    build:
      context: ./frontend/coresystemR
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: coresystem-frontend
    depends_on:
      - backend